### ISSUE TITLE
Legit aim assist good settings?

### ISSUE THREAD

**Issue by mind0r** [Jire/Charlatano#22]
Hey jire! Wich settings you would recomend, not so blatant, but like aim assisting settings, the defaults i try a bit but its hard. if you can advise some good settings i will apreaciate! Keep up the good work!
PS: CS:GO as updated today is the cheat still safe from vac? https://steamdb.info/app/730/

**Comment by keepo1337** [comment]
@mind0r Hey! I'm not Jire, but feel free to ask me, since Jire seems do be pretty busy lately. 
Do you mean 'legit' AimAssist-settings? First up, I would recommend turning off the aim key for the primary fire button (left mouse button). For this, you need to change the line 'ACTIVATE_FROM_FIRE_KEY = true' in the Aim.kts file to 'ACTIVATE_FROM_FIRE_KEY = false'.
For the aim strictness and aim speed I would recommend to leave it as it is (you may change the aim speed values a bit up, if you want slower aim), since it is really legit, although you might think it isnt.

To answer your second question: I played about 9 hours ago on european servers (I don't know if VAC is influenced by the region you play in) and the account hasn't got a VAC ban atm. It seems to be fully undetected for now. Great work from @jire

**Comment by mind0r** [comment]
Thanks for the answer :))
