### ISSUE TITLE
Stream proof esp giving black screen ?

### ISSUE THREAD

**Issue by HeyItsSanic** [Jire/Charlatano#52]
I have tried clicking left when black screen pops up but nothing happens ? It just stays there.. any suggestions ?

**Comment by stickywicky** [comment]
Same happens to me. I think its a dead hack. The dev hasnt replied in days.

**Comment by stickywicky** [comment]
UPDATE:
Heyitssanic, I had the same issue. I somewhat fixed this issue somehow... Go to the appdata and delete the downloaded files C:\Users\XXXXXX\AppData\Local\capsule\apps. Delete the Charlatano file. Then open up CS GO, load into a game. Then re-unzip the hack and rather than run the EXE. Run the .JAR file. Although they say not to do this, my hack loaded fine. 

Then when the hack has loaded run the exe while the hack is loaded from the JAR...

Then close the game and re-open. Then use the .exe from then on. Seemed to have worked for me personally...

**Comment by Jire** [comment]
Try with [1.0.1](https://github.com/Jire/Charlatano/releases/tag/1.0.1)
