### ISSUE TITLE
HOW DID YOU REVERSE ENGINEER THE VM OFFSETS?

### ISSUE THREAD

**Issue by jiachen247** [Jire/Charlatano#558]
Hi can i ask how you arrived at the offsets!!! I wanna start writing csgo cheats but don't know where to start.

**Comment by Jire** [comment]
All the info was found on forums

**Comment by jiachen247** [comment]
Awesome code by the way!!! 
Sorry this isnt really an 'issue'

**Comment by jiachen247** [comment]
@Jire May I know what forums this are? Or perhaps a place to start.

**Comment by 10urshin** [comment]
@jiachen247 https://www.unknowncheats.me/forum/counterstrike-global-offensive/103220-global-offensive-structs-offsets.html

@Jire How to fix findStudioModel in skeleton esp? type = 3 sanity check is true but it fails after that probably due to this change : https://www.unknowncheats.me/forum/counterstrike-global-offensive/271152-cs-update-breaking-cheats.html
